version: "3.3"

services:
#   aides-ai:
#     container_name: aides-ai
#     build:
#       context: .
#       dockerfile: ./docker/dev/ai.dockerfile
#     restart: on-failure
#     ports:
#       - 5000:5000
#     volumes:
#       - ./AI:/AIDES
#     env_file:
#       - .env

  aides-client:
    container_name: aides-client
    build: 
      context: .
      dockerfile: ./docker/dev/client.dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    env_file:
      - .env

  aides-db:
    container_name: aides-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT-5432}:5432

  aides-server:
    container_name: aides-server
    build: 
      context: .
      dockerfile: ./docker/dev/server.dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD-password}@aides-db:${DB_PORT-5432}/postgres