version: "3.3"

services:
  aides-client:
    container_name: aides-client
    build: 
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    env_file:
      - .env
    depends_on:
      - aides-server
  aides-server:
    container_name: aides-server
    build: 
      context: .
      dockerfile: ./docker/dev/server.dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
    env_file:
      - .env

