version: "3.3"

services:
  aides-ai:
    container_name: aides-ai
    build:
      context: .
      dockerfile: ./docker/dev/ai.dockerfile
    restart: on-failure
    volumes:
      - ./AI:/AIDES
    env_file:
      - .env
      
  aides-client:
    container_name: aides-client
    build: 
      context: .
      dockerfile: ./docker/dev/client.dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    env_file:
      - .env